name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Build the Docker image
      run: docker build -t krwiskow/docker-react -f Dockerfile.dev .
      
    - name: Run the test image
      run: docker run CI=true krwiskow/docker-react npm run test -- --coverage
