name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Build the Docker image
      run: docker build -t krwiskow/docker-react -f Dockerfile.dev .
      
    - name: Run the test image
      run: docker run -e CI=true krwiskow/docker-react npm run test -- --coverage

    - name: Generage deployment package
      run: zip -r deploy.zip . -x '*.git'

    - name: Deploy to Elasticbeanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react
        environment_name: docker-react-env
        existing_bucket_name: elasticbeanstalk-us-east-1-116112821534
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
